# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373


SENDGRID_USERNAME: martylavin1
SENDGRID_PASSWORD: Vickieelder2


GMAIL_USERNAME: martylavin1@gmail.com
GMAIL_PASSWORD: Vickieelder1