# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 265a5c47372e63633b1cb0df3f62daed2caed0d5959b252331e5a55414238c31dcc737560150c1fad3981bf0485b75a2c7a1df1edd47d4774ded68a4d716b75a

test:
  secret_key_base: 35fe7a61908732ac836a20744bf1255a0fc93f9b950f123a51984f0a150a7d98806169e582af81a04ed5c0cb0867c518b98bfc2468bd919d7c106dee0c56eaa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
